- name: configure picom
  command: "{{ item }}"
  args:
    chdir: "{{ picom_git_path }}"
    warn: false
  with_items:
    - rm -rf build
    - meson --buildtype=release . build

- name: build picom
  command: "{{ item }}"
  args:
    chdir: "{{ picom_git_path }}"
    warn: false
  with_items:
    - ninja -C build

- name: install picom
  command: "{{ item }}"
  args:
    chdir: "{{ picom_git_path }}"
    warn: false
  with_items:
    - nina -C build install
  
