- name: Install wpgtk
  pip:
    executable: pip3
    name: wpgtk
  become: yes
  become_user: root
  become_method: sudo

# - name: Ensure pywal is loaded
#   template:
#     src: pywal.bashrc.j2
#     dest: ~/.bashrc.d/50_pywal.bashrc

