# Add specified repository into sources list.
- name: Install apt repositories
  apt_repository:
    repo: ppa:papirus/papirus
  become: yes
  become_user: root
  become_method: sudo

- name: Install apt packages
  apt:
    name: "{{ rofi_shared_packages + rofi_build_dependencies }}"
    autoclean: True
    autoremove: True
    force_apt_get: True
    update_cache: True
    cache_valid_time: 3600
    install_recommends: False
  become: yes
  become_user: root
  become_method: sudo

- name: Ensure we have rofi cloned locally
  git:
    repo: "{{ rofi_git_repo }}"
    dest: "{{ rofi_git_path }}"
    version: "{{ rofi_git_ref }}"
    clone: True
    force: True
    recursive: True
    update: True
    depth: 1
  notify:
    - autoreconf rofi
    - configure rofi
    - build rofi
    - install rofi

- name: Symlink rofi configs
  file:
    src: "{{ dotfiles_home }}/roles/rofi/files/config"
    dest: "~/.config/rofi"
    state: link
